name: Jekyll Deploy

on: [push]

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
  GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

jobs: 
  buildAndDeploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build & Deploy to GitHub Pages
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
